const THREE_URL='https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.module.js';
(async()=>{
  const host=document.getElementById('uav-hero-canvas'); if(!host)return;
  const THREE=await import(THREE_URL);
  const scene=new THREE.Scene(); const camera=new THREE.PerspectiveCamera(34,1,.1,100); camera.position.set(.2,1.1,8.5);
  const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'}); renderer.setPixelRatio(Math.min(devicePixelRatio,1.8)); renderer.outputColorSpace=THREE.SRGBColorSpace; renderer.toneMapping=THREE.ACESFilmicToneMapping; renderer.toneMappingExposure=1.2; host.appendChild(renderer.domElement);
  scene.add(new THREE.HemisphereLight(0xffffff,0x64748b,2)); const key=new THREE.DirectionalLight(0xffffff,3.4); key.position.set(4,6,5); scene.add(key); const rim=new THREE.DirectionalLight(0x06b6d4,2.2); rim.position.set(-5,2,-4); scene.add(rim); const fill=new THREE.PointLight(0x6366f1,16,12); fill.position.set(1,2,3); scene.add(fill);
  const drone=new THREE.Group(); scene.add(drone); const white=new THREE.MeshStandardMaterial({color:0xe8edf5,metalness:.65,roughness:.24}); const dark=new THREE.MeshPhysicalMaterial({color:0x141a24,metalness:.8,roughness:.2,clearcoat:.45}); const shell=new THREE.MeshPhysicalMaterial({color:0x3b4655,metalness:.68,roughness:.25}); const glass=new THREE.MeshPhysicalMaterial({color:0x07111c,metalness:.1,roughness:.05,transmission:.25,transparent:true,opacity:.94,clearcoat:1}); const accent=new THREE.MeshStandardMaterial({color:0x06b6d4,emissive:0x06b6d4,emissiveIntensity:2.4,metalness:.4,roughness:.22});
  const add=(mesh,pos=[0,0,0],scale=null)=>{mesh.position.set(...pos); if(scale)mesh.scale.set(...scale); drone.add(mesh);return mesh};
  add(new THREE.Mesh(new THREE.SphereGeometry(1,48,24),dark),[-.05,.05,0],[1.75,.43,.78]); add(new THREE.Mesh(new THREE.SphereGeometry(1,40,20),shell),[1.55,.02,0],[1.05,.31,.62]); add(new THREE.Mesh(new THREE.SphereGeometry(1,36,20),glass),[.38,.39,0],[.72,.28,.5]);
  const wingGeo=new THREE.BoxGeometry(3.2,.09,.5); add(new THREE.Mesh(wingGeo,dark),[-.15,.03,1.25]); add(new THREE.Mesh(wingGeo,dark),[-.15,.03,-1.25]);
  add(new THREE.Mesh(new THREE.BoxGeometry(1.25,.09,.7),shell),[-1.65,.08,0],[1,1,.8]); add(new THREE.Mesh(new THREE.BoxGeometry(.7,.55,.08),dark),[-1.55,.55,0]);
  const rotors=[]; [[1.08,1.42],[1.08,-1.42],[-1.25,.88],[-1.25,-.88]].forEach(([x,z],i)=>{ add(new THREE.Mesh(new THREE.BoxGeometry(1.25,.12,.16),dark),[x*.58,.08,z*.58]).rotation.y=(i%2?-.42:.42); add(new THREE.Mesh(new THREE.CylinderGeometry(.23,.23,.22,32),dark),[x,.18,z]).rotation.x=Math.PI/2; add(new THREE.Mesh(new THREE.CylinderGeometry(.1,.1,.04,20),accent),[x,.3,z]).rotation.x=Math.PI/2; const r=new THREE.Group(); r.position.set(x,.34,z); for(let p=0;p<3;p++){const b=new THREE.Mesh(new THREE.BoxGeometry(1,.028,.11),white);b.position.x=.28;b.rotation.y=p*Math.PI*2/3;r.add(b)} drone.add(r);rotors.push(r)});
  add(new THREE.Mesh(new THREE.CylinderGeometry(.28,.24,.52,32),dark),[1.72,-.38,0]).rotation.z=Math.PI/2; add(new THREE.Mesh(new THREE.SphereGeometry(.12,24,12),accent),[2.02,-.38,0]);
  const clock=new THREE.Clock(); let mx=0,my=0,sx=0,sy=0; addEventListener('mousemove',e=>{mx=(e.clientX/innerWidth-.5)*2;my=(e.clientY/innerHeight-.5)*2},{passive:true});
  function resize(){const w=host.clientWidth||600,h=host.clientHeight||500;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false)} resize(); addEventListener('resize',resize,{passive:true});
  function animate(){requestAnimationFrame(animate);const t=clock.getElapsedTime();sx+=(mx-sx)*.045;sy+=(my-sy)*.045;drone.position.y=Math.sin(t*1.15)*.09;drone.rotation.y=Math.sin(t*.35)*.18+sx*.28;drone.rotation.x=sy*.08+Math.sin(t*.5)*.025;drone.rotation.z=-sx*.04;rotors.forEach((r,i)=>r.rotation.y=t*(i%2?-45:45));fill.position.x=1+sx*2;fill.position.y=2-sy*1.3;renderer.render(scene,camera)} animate();
})();
